export const CHART_THEME = {
  axisStroke: '#7c8ea8',
  axisFontSize: 10,
  gridStroke: '#5f7596',
  gridOpacity: 0.2,
  gridDasharray: '3 5',
  daySeparatorStroke: '#7f95b6',
  daySeparatorDasharray: '3 3',
  daySeparatorWidth: 1.5,
  daySeparatorOpacity: 0.5,
  dayLabelColor: '#8ea3c4',
  dayLabelFontSize: 13,
  nowMarkerStroke: '#0284c7',
  nowMarkerLabelColor: '#38bdf8',
  nowMarkerWidth: 3,
  nowMarkerOpacity: 0.85,
  selectedMarkerStroke: '#0ea5e9',
  selectedMarkerWidth: 2,
  selectedMarkerOpacity: 0.65,
  futureAreaFill: '#0ea5e9',
  futureAreaOpacity: 0.08,
  baselineStroke: '#7c8ea8',
  baselineWidth: 1,
  tooltipBackground: '#ffffff',
  tooltipBorder: '#e2e8f0',
  tooltipRadius: 12,
} as const

export const CHART_LAYOUT = {
  forecastHeightClass: 'h-80',
  buoyHeightClass: 'h-60 min-h-[236px]',
  leftAxisWidth: 42,
  forecastRightAxisWidth: 35,
  buoyRightAxisWidth: 42,
  rightAxisTickCount: 5,
  buoyLeftAxisTickCount: 6,
} as const

export const CHART_SERIES_COLORS = {
  height: '#38bdf8',
  energy: '#fbbf24',
  period: '#fbbf24',
  wavePeriod: '#22c55e',
  windSpeed: '#3b82f6',
  windDirection: '#0284c7',
} as const
